src/Entity/Fixer.php
<?php

namespace App\Entity;

use App\Repository\FixerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FixerRepository::class)
 */
class Fixer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Fixer;
use App\Entity\Locale;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Count;
use Symfony\Component\Validator\Constraints\NotBlank;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(Request $request, EntityManagerInterface $em)
    {
        $fixedContent = '';
        $toFixContent = '';

        $form = $this->createFormBuilder(['Fixer'])
            ->add('locales', EntityType::class, [
                'class' => Locale::class,
                'choice_label' => 'name',
            ])
            ->add('fixers', EntityType::class, [
                'class' => Fixer::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
                'constraints' => new Count(['min' => 1, 'minMessage' => 'You should select at least one fixer']),
            ])
            ->add('toFixContent', TextareaType::class, [
                'constraints' => new NotBlank(),
                'label' => false,
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Try',
            ])
            ->getForm();

        if ($request->isMethod('POST')) {
            $form->submit($request->request->get($form->getName()));

            if ($form->isSubmitted() && $form->isValid()) {
                $toFixContent = $form->getData()['toFixContent'];
                $fixers = $form->getData()['fixers']->map(function (Fixer $fixer) {
                    return $fixer->getName();
                })->toArray();
                $fixer = new \JoliTypo\Fixer($fixers);
                $fixer->setLocale($form->getData()['locales']->getName());
                $fixedContent = $fixer->fix($toFixContent);
            }
        }

        $fixers = $em->getRepository(Fixer::class)->findAllSortedByName();

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'form' => $form->createView(),
            'fixedContent' => $fixedContent,
            'toFixContent' => $toFixContent,
            'fixers' => $fixers,
            'jolitypo_lib_link' => 'https://github.com/jolicode/JoliTypo',
        ]);
    }
}

templates/home/docs.html.twig
<section class="u-mb(lg)">
    <h2 class="u-c(docs)">DOCS</h2>
    <h3>Fixers</h3>

    <div class="o-grid u-pt(base)">
        {% for fixer in fixers %}
        <div class="o-grid__col o-grid__col--7">
            <p class="c-fixer__name">{{ fixer.name }}</p>
            <p class="c-fixer__description">{{ fixer.description }}</p>
        </div>
        <div class="o-grid__col o-grid__col--push-1 o-grid__col--4">
            <img src="https://picsum.photos/300/200" alt="">
        </div>
        {% endfor %}
    </div>
</section>

templates/home/footer.html.twig
<footer class="u-mb(base)">
    <img src="{{ asset('build/images/logo.svg') }}" alt="logo JoliTypo" width="200" height="200">
    <div class="u-d(flex) u-jc(space-between) u-ai(center) u-mt(base)">
       <span>&#xA9; 2010 - {{ 'now'|date('Y') }}</span>
        <span>Made By Damien Alexandre with ❤️</span>
        <button class="c-button"><a href="{{ jolitypo_lib_link }}">Github</a></button>
    </div>
</footer>

templates/home/glossary.html.twig
<section class="u-mb(lg)">
    <h2 class="u-c(glossary) u-mb_min15">GLOSSARY</h2>
    <div class="o-grid u-ai(center) u-mt(lg)@tablet-down u-pt(sm)">
        <div class="o-grid__col o-grid__col--6 glo">
            <p>Thanks to theses online resources for helping a developer understand typography:</p>
            <p>🇫🇷
                http://typographisme.net/post/Les-espaces-typographiques-et-le-web
                http://dascritch.net/post/2011/05/09/Les-espacements-unicodes
                http://www.uzine.net/article1802.html
                « Abrégé du code typographique à l’usage de la presse », ISBN: 9782351130667</p>
            <p>🇬🇧
                http://daringfireball.net/projects/smartypants/
                https://en.wikipedia.org/wiki/Non-English_usage_of_quotation_marks
                http://www.punctuationmatters.com/ is a must read
                http://practicaltypography.com/</p>
        </div>
        <div class="o-grid__col o-grid__col--6">
            <img src="{{ asset('build/images/reading_man.svg') }}" alt="" width="100%">
        </div>
    </div>
</section>

templates/home/header.html.twig
<header class="o-grid u-mb(md)">
    <div class="o-grid__col o-grid__col--12 u-fxd(column) u-ai(center) u-d(flex)">
        <h1 class="u-mb(base)">
            <a href=""><img src="{{ asset('build/images/logo.svg') }}" alt="JoliTypo logo" width="200px" height="200px"></a>
        </h1>
        <div>
            <img src="https://poser.pugx.org/jolicode/jolitypo/v" alt="">
            <img src="https://poser.pugx.org/jolicode/jolitypo/downloads" alt="">
            <img src="https://poser.pugx.org/jolicode/jolitypo/license" alt="">
            <img src="https://poser.pugx.org/jolicode/jolitypo/v/unstable" alt="">
        </div>
        <p class="c-subtitle u-mb(base)">Jolitypo is a tool fixing Microtypography glitches inside your HTML content</p>
        <button class="c-button"><a href="{{ jolitypo_lib_link }}" target="_blank">Github</a></button>
    </div>
</header>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}JoliTypo{% endblock %}

{% block body %}
    {{ include('home/header.html.twig') }}
    {{ include('home/try.html.twig') }}
    {{ include('home/docs.html.twig') }}
    {{ include('home/used_by.html.twig') }}
    {{ include('home/glossary.html.twig') }}
    {{ include('home/footer.html.twig') }}
{% endblock %}

templates/home/try.html.twig
<section class="u-mb(lg)">
    <h2 class="u-c(try) u-mb(base)">TRY IT</h2>
    {{ form_start(form) }}
    <div class="error">
        {{ form_errors(form) }}
    </div>
    <div class="o-grid">
        <div class="o-grid__col o-grid__col--5">
            <div class="select u-mb(base)">
                {{ form_row(form.locales, {'attr': {'class': 'locale_field u-d(block) u-c(try)'}}) }}
            </div>

            <div class="box">
                {{ form_row(form.fixers, {'attr': {'class': 'fixer_fields u-d(flex) u-fxw(wrap) u-ac(space-between)'}}) }}
            </div>
        </div>
        <div class="o-grid__col o-grid__col--6 o-grid__col--push-1">
            {{ form_row(form.toFixContent, {'attr': {'class': 'to_fix_content_field'}}) }}
            {{ form_row(form.submit, {'attr': {'class': 'u-w(100) c-button'}}) }}
            {{ form_end(form) }}
            <div class="js-fixed-content fixed-content" data-is-fixed="{{ fixedContent }}" data-is-to-fix="{{ toFixContent }}"><pre><code>{{ fixedContent }}</code></pre></div>
            <div class="diff"><pre ><code id="js-display"></code></pre></div>
        </div>
    </div>
</section>

templates/home/used_by.html.twig
<section class="u-mb(lg)">
    <h2 class="u-c(used_by) u-mb(md)">USED BY</h2>
    <div class="u-d(flex) u-ai(center) u-jc(space-around) u-pt(base) u-fxw(wrap)">
        {% for i in 0..4 %}
                <img class="u-pl(base) u-pr(base)" src="https://picsum.photos/500/500" alt="">
        {% endfor %}
    </div>
</section>